### ISSUE TITLE
Question about type conversion in `RNSqlite2.m`

### ISSUE THREAD

**Issue by nikki93** [craftzdog/react-native-sqlite-2#1]
Hi!

In `RNSqlite2.m`: https://github.com/noradaiko/react-native-sqlite-2/blob/3d3efd0fbf3b39199a6c83c934f361df3c604c5c/ios/RNSqlite2.m#L239-L241

Wouldn't we never hit the `sqlite3_bind_int64(...)` call because numbers always convert to floating point in JS or at least in JS -> native conversion?

**Comment by noradaiko** [comment]
It will hit that code if given numeral data was an integer.

I confirmed that `1` in JS would be converted to `long` in ObjC and `1.1` would be `double`.
