### ISSUE TITLE
WebSQL threw an error [Error: Error code 1: no such table: document-store]

### ISSUE THREAD

**Issue by special-character** [craftzdog/react-native-sqlite-2#100]
Thanks for the project!

We are using this with RxDB and started getting this error somewhat sporadically. It seems to happen after we remove the database. I was surprised to see this was a WebSQL error. I don't have great ways to debug this but my hunch is that we have some code that still tries to access the now dead database. Asking here because this is he only lib we have that uses WebSQL.

Has anyone ran into this kind of error or know what might be the cause?

Thanks for any help/suggestions.

**Comment by craftzdog** [comment]
I guess your app or RxDB tries to query before it creates the database `document-store`.
You should check your code or ask RxDB for help.
