### ISSUE TITLE
module installation broken

### ISSUE THREAD

**Issue by matinzd** [craftzdog/react-native-sqlite-2#112]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-sqlite-2'.
> Could not resolve all artifacts for configuration ':react-native-sqlite-2:classpath'.
   > Could not resolve com.android.tools.build:gradle:2.3.+.
     Required by:
         project :react-native-sqlite-2
      > Failed to list versions for com.android.tools.build:gradle.
         > Unable to load Maven meta-data from https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml.
            > Could not HEAD 'https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml'. Received status code 502 from server: Bad Gateway

**Comment by dfrancio** [comment]
same here.

to temporary solve till mantenedor do a fix, I changed version of gradle in react-native-sqlite-2/android/build.gradle from 2.3.+ to 3.1.4.

hope this help you.
Regards

**Comment by matinzd** [comment]
Thanks, I did the same thing, I may open a PR for it.

**Comment by jcastrol** [comment]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':react-native-sqlite-2'.
> Could not resolve all artifacts for configuration ':react-native-sqlite-2:classpath'.
   > Could not resolve com.android.tools.build:gradle:3.1.4.
     Required by:
         project :react-native-sqlite-2
      > Could not resolve com.android.tools.build:gradle:3.1.4.
         > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom'.
            > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/3.1.4/gradle-3.1.4.pom'. Received status code 502 from server: Bad Gateway
