### ISSUE TITLE
How to use update statement??

### ISSUE THREAD

**Issue by zGuindouGit** [craftzdog/react-native-sqlite-2#12]
How can I use update statement in this react native sqlite 2 ??

@craftzdog 
@Kudo 
@hnq90 
@sammacbeth

**Comment by craftzdog** [comment]
Just google with 'sqlite update statement'.
Do not be spammy with bulk mentions.

**Comment by zGuindouGit** [comment]
Thanks++ for your **great** response Mr. @craftzdog
