### ISSUE TITLE
[Windows] Uses private APIs?

### ISSUE THREAD

**Issue by metalmalte** [craftzdog/react-native-sqlite-2#13]
When validating with the Windows App Certification Kit, I run into a problem at the check for private APIs.
I cannot upload a windows app to the store, because it tells me, sqlite uses internal APIs, as seen in the error list. Anyone up with a solution for this?

API AreFileApisANSI in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileMappingA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileMappingW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API CreateFileW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API GetFileSize in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API GetFullPathNameA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API GetModuleHandleA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API GetTempPathA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API GetVersionExA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API GetVersionExW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API HeapValidate in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API LoadLibraryA in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API LoadLibraryW in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API LockFile in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API MapViewOfFile in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API UnhandledExceptionFilter in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API UnlockFile in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API VirtualProtect in kernel32.dll is not supported for this application type. sqlite3.dll calls this API.
API __dllonexit in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API __setusermatherr in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API _amsg_exit in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API _beginthreadex in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API _endthreadex in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API _errno in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API _initterm in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API _iob in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API _lock in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API _onexit in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API _unlock in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API abort in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API calloc in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API fprintf in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API free in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API fwrite in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API localtime in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API malloc in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API memcmp in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API memmove in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API qsort in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API realloc in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API strcmp in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API strlen in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API strncmp in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.
API vfprintf in msvcrt.dll is not supported for this application type. sqlite3.dll calls this API.

**Comment by craftzdog** [comment]
Maybe related: https://github.com/aspnet/EntityFrameworkCore/issues/6905

**Comment by craftzdog** [comment]
No response. Closing.
