### ISSUE TITLE
Build error with RN 0.69.2 - minSdk version conflict

### ISSUE THREAD

**Issue by Ruslan-Mz** [craftzdog/react-native-sqlite-2#131]
Hello!

I have an issue with building the app in Azure Pipelines after upgrading to react-native 0.69.2 (using old architecture, not new), It was building and working fine with 0.67.4.

Build error says there's a conflict between minSdkVersion of the library and react-native version:
```
* What went wrong:
Execution failed for task ':react-native-sqlite-2:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-native:0.69.2] /Users/runner/.gradle/caches/transforms-3/1ecf169629d825591b5487eeb6e62473/transformed/jetified-react-native-0.69.2-debug/AndroidManifest.xml as the library might be using APIs not available in 16
  	Suggestion: use a compatible library with a minSdk of at most 16,
  		or increase this project's minSdk version to at least 21,
  		or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)
```

Main minSdkVersion in my build.gradle is set to 21, same as react-native library. Bur your build.gradle says 16.
There should not be an error though, because it will be overriden by manifest merge. But there is...
My assumption it's because of the nesting dependency of react-native inside your build.gradle. 
```
dependencies {
  implementation 'com.facebook.react:react-native:+'
  api 'androidx.sqlite:sqlite:2.1.0'
  implementation 'com.github.requery:sqlite-android:3.36.0'
}

```
So the build process checks this hierarchy first, and find a conflict between your library and dependency.
You define minSdk as 16, but maybe it's possible to use the one from the main project? As you do with target sdk?
```
defaultConfig {
    minSdkVersion 16
    targetSdkVersion rootProject.hasProperty('targetSdkVersion') ? rootProject.targetSdkVersion : DEFAULT_TARGET_SDK_VERSION
    versionCode 1
    versionName "1.6.2"
  }
```

I've tried to override library use-sdk from manifest, but no luck. Probably because it's a nested dependency conflict that is checked before overriding from main manifest.

Same issue was with other library, and it was fixed by using same approach as for targetSdkVersion

**Comment by craftzdog** [comment]
Can you try 3.6.0-beta.1?

**Comment by Ruslan-Mz** [comment]
Hi @craftzdog!

Do I need to make some additional adjustments?
Because now with beta.1 I have this issue:
```
> Task :app:compileDebugJavaWithJavac
/Users/runner/work/1/s/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:53: error: cannot find symbol
import com.reactnativesqlite2.RNSqlite2Package;
                             ^
  symbol:   class RNSqlite2Package
  location: package com.reactnativesqlite2
/Users/runner/work/1/s/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:124: error: cannot find symbol
      new RNSqlite2Package(),
          ^
  symbol:   class RNSqlite2Package
  location: class PackageList

```
P.S. main project now uses Java 11, because RN 0.69 needs it. I see that library uses JavaVersion.VERSION_1_8, but I'm not sure if issue is here.

**Comment by craftzdog** [comment]
run `./gradlew clean` and try again

**Comment by Ruslan-Mz** [comment]
Still same. Tried several times, cleaned everything, reinstalled node modules, restarted. No luck.
And this issue occurs both locally and in Azure builder, that removes everything before each launch.
Changing your java version to 11 in beta.1 didn't help.
But If I change minSdkVersion to 21 manually in 3.5.2, then this issue does not occur.

**Comment by Ruslan-Mz** [comment]
Hi @craftzdog 
Can you please release a minor update only with minSdkVersion version update?

**Comment by craftzdog** [comment]
I'll work on it next week

**Comment by Ruslan-Mz** [comment]
Thank you!

**Comment by craftzdog** [comment]
Can you try 3.6.0-beta.2?
Found and fixed an issue in the manifest file: https://github.com/craftzdog/react-native-sqlite-2/commit/9926fe80927b76eb6a2acdfeb33e163113026d14

**Comment by Ruslan-Mz** [comment]
Thank you! It works!!!

**Comment by Ruslan-Mz** [comment]
Do you know approximately how long the new version will be in beta? Is there much left to implement/fix?

**Comment by craftzdog** [comment]
There are no breaking changes, so it should be ready now.

**Comment by craftzdog** [comment]
v3.6.0 has landed. Thanks for the report.

**Comment by Ruslan-Mz** [comment]
thank you!
