### ISSUE TITLE
Windows - react-native-sqlite-2 gives issues with autolink-windows where react-native version is 0.68

### ISSUE THREAD

**Issue by Manjunatha123** [craftzdog/react-native-sqlite-2#134]
I am getting this error when i run `npx react-native run-windows`
react-native-sqlite-2 has Windows implementation, config:
{
  folder: '<<project folder>>\node_modules\\react-native-sqlite-2',
  projects: [],
  solutionFile: null,
  nugetPackages: [],
  sourceDir: 'windows'
}
 × Auto-linking...
Error: Autolinking: Found a Windows solution for react-native-sqlite-2 but no React Native for Windows native module projects. (2047ms)
Command failed with error Autolinking: Found a Windows solution for react-native-sqlite-2 but no React Native for Windows native module projects

Please find the results of `npx react-native info`
System:
    OS: Windows 10 10.0.19042
    CPU: (8) x64 Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz
    Memory: 8.57 GB / 16.00 GB
  Binaries:
    Node: 16.14.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.16.0 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.14393.0, 10.0.16299.0, 10.0.17763.0, 10.0.18362.0, 10.0.19041.0, 10.0.20348.0, 10.0.22000.0, 10.0.22621.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 17.2.32630.192 (Visual Studio Enterprise 2022), 15.9.28307.2019 (Visual Studio Enterprise 2017)
  Languages:
    Java: Not Found
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.68.0 => 0.68.0
    react-native-windows: 0.68.0 => 0.68.0
  npmGlobalPackages:
    *react-native*: Not Found

**Comment by Manjunatha123** [comment]
Also Please find node and npm versions
C:\Users\user1>node -v
v16.14.1

C:\Users\user1>npm -v
8.16.0

**Comment by KshamaShrey** [comment]
Even I am facing the same issue.Could you please resolve it as soon as possible.Thanks

**Comment by craftzdog** [comment]
I don't use Windows. PR would be appreciated

**Comment by Manjunatha123** [comment]
When we had react-native version as 0.57.2 and react-native-windows version as 0.57.2 it was working for windows.
Please find the package version informations
    "react-native": "0.57.2",
    "react-native-sqlite-2": "1.7.0",
    "react-native-windows": "^0.57.2",
But with the latest version of react-native 0.68 Its throwing errors while autolinking.
Any suggestions on this regard would be appreciated.
If this is not supporting windows could you suggest any alternatives that we can check which supports windows android and ios?

thanks.

**Comment by craftzdog** [comment]
https://github.com/craftzdog/react-native-sqlite-2/commit/9d3824bfdcfff07a435b88f95c45404cca2ea847 should fix this

**Comment by Manjunatha123** [comment]
Hi, Thanks for the solution.
Sorry there was no luck updating the version to 3.6.1.
Let me put the steps I followed
```
npx react-native init MyApp --template react-native@0.68.0
cd ./MyApp/
npx react-native-windows-init --overwrite --version 0.68.0 --language cs
```
Installed the packages using the command
`npm i <package name> --save`

package.json looks like below
```
{
  "name": "MyApp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start --reset-cache",
    "test": "jest",
    "lint": "eslint .",
    "windows": "react-native run-windows --logging"
  },
  "dependencies": {
    "@react-native-community/netinfo": "^9.3.0",
    "@react-native-picker/picker": "^2.4.3",
    "@react-navigation/native-stack": "^6.7.0",
    "ajv": "^8.11.0",
    "ajv-errors": "^3.0.0",
    "ajv-keywords": "^5.1.0",
    "axios": "^0.27.2",
    "deprecated-react-native-listview": "^0.0.8",
    "isaac": "^0.0.5",
    "moment": "^2.29.4",
    "moment-with-locales-es6": "^1.0.1",
    "react": "17.0.2",
    "react-native": "0.68.0",
    "react-native-background-fetch": "^4.1.2",
    "react-native-bcrypt": "^2.4.0",
    "react-native-circular-progress": "^1.3.7",
    "react-native-device-info": "^10.0.2",
    "react-native-extended-stylesheet": "^0.12.0",
    "react-native-modal": "^13.0.1",
    "react-native-modal-dropdown": "^1.0.2",
    "react-native-popup-menu": "^0.15.12",
    "react-native-render-html": "^6.3.4",
    "react-native-simple-modal": "^9.0.1",
    "react-native-sqlite-2": "^3.6.1",
    "react-native-swipe-list-view": "^3.2.9",
    "react-native-tab-view": "^3.1.1",
    "react-native-vector-icons": "^9.2.0",
    "react-native-windows": "0.68.0",
    "react-redux": "^8.0.2",
    "redux": "^4.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/plugin-external-helpers": "^7.18.6",
    "@babel/preset-env": "^7.18.10",
    "@babel/preset-react": "^7.18.6",
    "@babel/runtime": "^7.12.5",
    "@react-native-community/eslint-config": "^2.0.0",
    "babel-jest": "^26.6.3",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-config": "^0.67.0",
    "metro-react-native-babel-preset": "^0.67.0",
    "react-test-renderer": "17.0.2",
    "uuid": "^8.3.2"
  },
  "jest": {
    "preset": "react-native"
  }
}
```
Please find the complete error log after running react-native run-windows command

PS C:\MyApp> npm run windows

> MyApp@0.0.1 windows
> react-native run-windows --logging

 i Verbose: ON
Looking for vswhere at: C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe
 √ Found compatible MSBuild at C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin (17.2.32630.192)
 Microsoft (R) Build Engine version 17.2.1+52cd2da31 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
Build started 8/11/2022 2:35:56 PM.
Project "C:\Users\user1\\MyApp\\MyApp\windows\MyApp.sln" on node 1 (Restore
 target(s)).
ValidateSolutionConfiguration:
  Building solution configuration "Debug|x64".
C:\Users\user1\\MyApp\\MyApp\node_modules\react-native-windows\PropertyShee
ts\JSEngine.props(4,3): warning MSB4011: "C:\Users\user1\\MyApp\\MyApp\wind 
ows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "C:\Users\user1\\MyApp\\MyApp\windows\MyApp\MyApp.csproj (5,3)". This is most likely a build authori 
ng error. This subsequent import will be ignored.
_GetAllRestoreProjectPathItems:
  Determining projects to restore...
Done Building Project "C:\Users\user1\\MyApp\\MyApp\windows\MyApp.sln" (Res
tore target(s)).


Build succeeded.

  C:\Users\user1\\MyApp\\MyApp\node_modules\react-native-windows\PropertySh 
eets\JSEngine.props(4,3): warning MSB4011: "C:\Users\user1\\MyApp\\MyApp\wi 
ndows\ExperimentalFeatures.props" cannot be imported again. It was already imported at "C:\Users\user1\\MyApp\\MyApp\windows\MyApp\MyApp.csproj (5,3)". This is most likely a build autho 
ring error. This subsequent import will be ignored.

    1 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.34
√ Restoring NuGet packages 
- Auto-linking...
Parsing project...
Found Windows app project, config:
{
  folder: 'C:\\Users\\user1\\\\MyApp\\\\MyApp',
  sourceDir: 'windows',
  solutionFile: 'MyApp.sln',
  project: {
    projectFile: 'MyApp\\MyApp.csproj',
    projectName: 'MyApp',
    projectLang: 'cs',
    projectGuid: '{2D7A7CC3-AA3B-4BC4-9B4A-35973C394725}'
  },
  experimentalFeatures: {
    UseHermes: 'false',
    UseWinUI3: 'false',
    UseExperimentalNuget: 'false'
  }
}
Parsing dependencies...
@react-native-community/netinfo has Windows implementation, config:
{
  folder: 'C:\\Users\\user1\\\\MyApp\\\\MyApp\\node_modules\\@react-native-community\\netinfo',
  projects: [
    {
      projectFile: 'RNCNetInfoCPP\\RNCNetInfoCPP.vcxproj',
      projectName: 'RNCNetInfoCPP',
      projectLang: 'cpp',
      projectGuid: '{37e37094-01b3-44a5-aab7-f0379b1ce8fa}',
      directDependency: true,
      cppHeaders: [Array],
      cppPackageProviders: [Array],
      csNamespaces: [Array],
      csPackageProviders: [Array]
    }
  ],
  solutionFile: 'RNCNetInfo.sln',
  nugetPackages: [],
  sourceDir: 'windows'
}
Adding @react-native-community/netinfo.
@react-native-picker/picker has Windows implementation, config:
{
  folder: 'C:\\Users\\user1\\\\MyApp\\\\MyApp\\node_modules\\@react-native-picker\\picker',
  projects: [
    {
      projectFile: 'ReactNativePicker\\ReactNativePicker.vcxproj',
      projectName: 'ReactNativePicker',
      projectLang: 'cpp',
      projectGuid: '{bedcc600-4541-41f2-aa46-9e058202b6ad}',
      directDependency: true,
      cppHeaders: [Array],
      cppPackageProviders: [Array],
      csNamespaces: [Array],
      csPackageProviders: [Array]
    }
  ],
  solutionFile: 'ReactNativePicker.sln',
  nugetPackages: [],
  sourceDir: 'windows'
}
Adding @react-native-picker/picker.
react-native-device-info has Windows implementation, config:
{
  folder: 'C:\\Users\\user1\\\\MyApp\\\\MyApp\\node_modules\\react-native-device-info',
  projects: [
    {
      projectFile: 'RNDeviceInfoCPP\\RNDeviceInfoCPP.vcxproj',
      projectName: 'RNDeviceInfoCPP',
      projectLang: 'cpp',
      projectGuid: '{3e3931f2-4735-4417-8cb0-33668a7314d6}',
      directDependency: true,
      cppHeaders: [Array],
      cppPackageProviders: [Array],
      csNamespaces: [Array],
      csPackageProviders: [Array]
    }
  ],
  solutionFile: 'RNDeviceInfoCPP.sln',
  nugetPackages: [],
  sourceDir: 'windows'
}
Adding react-native-device-info.
react-native-sqlite-2 has Windows implementation, config:
{
  folder: 'C:\\Users\\user1\\\\MyApp\\\\MyApp\\node_modules\\react-native-sqlite-2',
  projects: [],
  solutionFile: 'RNSqlite2.sln',
  nugetPackages: [],
  sourceDir: 'windows'
}
 × Auto-linking...
Error: Autolinking: Found a Windows solution for react-native-sqlite-2 but no React Native for Windows native module projects. (1740ms)
 × Autolinking failed. Found a Windows solution for react-native-sqlite-2 but no React Native for Windows native module projects
 i Gathering MSBuild data for telemetry.
 i Loading properties from msbuildproperties.g.json
Command failed with error Autolinking: Found a Windows solution for react-native-sqlite-2 but no React Native for Windows native module projects
Your telemetry sessionId was xxxxx

**Comment by Manjunatha123** [comment]
@craftzdog - Could you please check the comment above?
