### ISSUE TITLE
support react-native 0.47+

### ISSUE THREAD

**Issue by mmerickel** [craftzdog/react-native-sqlite-2#14]
The library currently claims a pin to 0.41.2. Can this be updated safely?

**Comment by f4z3k4s** [comment]
I created a PR. There was only one breaking change from v0.41.2 to v0.47. If you checkout my PR, it'll work with 0.47, you can use it until it is merged.

**Comment by craftzdog** [comment]
Please use v1.5.0 which is tested on RN 0.48.0.
You can also check if it works with tests: https://github.com/craftzdog/react-native-sqlite-2/tree/master/test

**Comment by mmerickel** [comment]
Thank you! Unfortunately I need to stick with react-native-sqlite-storage for now as it provides directly access to the database. There are some pragmas that cannot be set while inside a transaction which are important to me. So I have to use the direct api to startup and then switch to transactions for normal app logic and I don't see a way to accomplish this with react-native-sqlite-2 via simply the websql api. :-(
