### ISSUE TITLE
ld: symbol(s) not found for architecture x86_64

### ISSUE THREAD

**Issue by KrantiKadam** [craftzdog/react-native-sqlite-2#16]
Getting following linking error:

Undefined symbols for architecture x86_64:
  "_sqlite3_bind_double", referenced from:
      -[RNSqlite2 bindStatement:withArg:atIndex:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_bind_int64", referenced from:
      -[RNSqlite2 bindStatement:withArg:atIndex:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_bind_null", referenced from:
      -[RNSqlite2 bindStatement:withArg:atIndex:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_bind_text", referenced from:
      -[RNSqlite2 bindStatement:withArg:atIndex:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_close", referenced from:
      -[RNSqlite2 dealloc] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_column_bytes", referenced from:
      -[RNSqlite2 getSqlValueForColumnType:withStatement:withIndex:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_column_count", referenced from:
      -[RNSqlite2 executeSql:withSqlArgs:withDb:withReadOnly:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_column_double", referenced from:
      -[RNSqlite2 getSqlValueForColumnType:withStatement:withIndex:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_column_int64", referenced from:
      -[RNSqlite2 getSqlValueForColumnType:withStatement:withIndex:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_column_name", referenced from:
      -[RNSqlite2 executeSql:withSqlArgs:withDb:withReadOnly:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_column_text", referenced from:
      -[RNSqlite2 getSqlValueForColumnType:withStatement:withIndex:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_column_type", referenced from:
      -[RNSqlite2 executeSql:withSqlArgs:withDb:withReadOnly:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_errcode", referenced from:
      +[RNSqlite2 convertSQLiteErrorToString:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_errmsg", referenced from:
      +[RNSqlite2 convertSQLiteErrorToString:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_finalize", referenced from:
      -[RNSqlite2 executeSql:withSqlArgs:withDb:withReadOnly:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_last_insert_rowid", referenced from:
      -[RNSqlite2 executeSql:withSqlArgs:withDb:withReadOnly:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_open", referenced from:
      -[RNSqlite2 openDatabase:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_prepare_v2", referenced from:
      -[RNSqlite2 executeSql:withSqlArgs:withDb:withReadOnly:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_step", referenced from:
      -[RNSqlite2 executeSql:withSqlArgs:withDb:withReadOnly:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_stmt_readonly", referenced from:
      -[RNSqlite2 executeSql:withSqlArgs:withDb:withReadOnly:] in libRNSqlite2.a(RNSqlite2.o)
  "_sqlite3_total_changes", referenced from:
      -[RNSqlite2 executeSql:withSqlArgs:withDb:withReadOnly:] in libRNSqlite2.a(RNSqlite2.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Is anyone facing the same issue for using 'react-native-sqlite-2' for iOS react-native app?

**Comment by craftzdog** [comment]
Link `libsqlite3.tbd` to your project
https://github.com/craftzdog/react-native-sqlite-2#ios

**Comment by craftzdog** [comment]
No response. Closing.
