### ISSUE TITLE
Plugin usage with pouchdb

### ISSUE THREAD

**Issue by drunksaint** [craftzdog/react-native-sqlite-2#2]
Hi

How do we use this plugin with pouchdb? This doesn't seem to be working:
```
import PouchDB from 'pouchdb-react-native';
PouchDB.plugin(require('react-native-sqlite-2'));
testdb = new PouchDB('test', {adapter:'websql'});
```
Thanks

**Comment by craftzdog** [comment]
Hi,

I added an instruction of the usage with pouchdb:
https://github.com/craftzdog/react-native-sqlite-2#using-with-pouchdb

**Comment by drunksaint** [comment]
Thanks!
