### ISSUE TITLE
Visual studio issue

### ISSUE THREAD

**Issue by sm2017** [craftzdog/react-native-sqlite-2#20]
For windows  , I follow install instruction , It works before well (I installed it for months)

But today I have the following error

| Severity | Code   | Description | Project   | File | Line | Suppression State |
|----------|--------|-------------|-----------|------|------|-------------------|
| Error    | CS0006 |  Metadata file 'C:\projects\MyProject\node_modules\react-native-sqlite-2\windows\RNSqlite2\bin\x64\Debug\RNSqlite2.dll' could not be found           | MyProject | CSC  | 1    | Active            |

I clean / rebuild / unload and load project , but always I have this error

**Comment by hnq90** [comment]
@sm2017 Which version are you using?

**Comment by sm2017** [comment]
@hnq90 visual studio 2017 15.0.0

**Comment by sm2017** [comment]
@hnq90 How can I solve it?

**Comment by hnq90** [comment]
@sm2017 The above issue didn't occur on my local. Could you try it on a simple app?

**Comment by craftzdog** [comment]
No response. Closing.
