### ISSUE TITLE
How do you guys manage schema changes in your production apps? 

### ISSUE THREAD

**Issue by spruce-bruce** [craftzdog/react-native-sqlite-2#23]
Sorry for this question which doesn't have anything to do with the library, but do you guys have a library for managing schema changes or are you doing something like storing a schema version in the db and writing your own "migration" logic?

**Comment by craftzdog** [comment]
I’m using it as a storage engine for PouchDB which is a schema-less database. So I don’t use this directly.

It’d be useful if you wrote a library something like this: [node-sqlite](https://github.com/kriasoft/node-sqlite/blob/master/README.md#migrations)
I’m not sure if it works on RN.

**Comment by spruce-bruce** [comment]
Thanks for the response!

I actually hacked together something that works similarly (no down migrations, though, because I think they're evil). I'll publish it and link it back here and close this issue when I do

**Comment by FunMiles** [comment]
I personally handle schema changes with a transaction but I don't know how to really make it work perfectly with this library. The procedure is like this:

    PRAGMA foreign_keys=off;
    ALTER TABLE tblName RENAME TO tblName_tmp;
    CREATE TABLE tblName <table creation commands here>;
    c1 = [ Code to get the column names for tblName_tmp ]
    c2 = [ Code to get column names for tblName]
    rc = [ Code to obtain the array of retained columns, being the intersection of c1 and c2]
    INSERT INTO tblName ( <rc> ) SELECT <rc> FROM tblName_tmp;
    DROP TABLE tmbName_tmp;
    PRAGMA foreight_keys=on;

Normally, to obtain the column names, I use 'pragma table_info( tblName )' and retrieve the name field in each row of the query. 
Unfortunately I don't see how I can do this pragma in the middle of this library's transaction and obtain the result. Is there a way to handle this properly?
As a back up, I've gone for splitting the work into several transactions. But that raises the issue that while the work is being done, the database state goes through invalid states from the point of view of database users.

**Comment by spruce-bruce** [comment]
I never packaged my migration stuff up, and I'm in the process of ripping it out of my app (changing requirements, etc). I didn't want to delete it so I threw it into a gist with some less-than-adequate notes about usage.

Hopefully you guys will find it useful: https://gist.github.com/spruce-bruce/97ed3d0fddab3a93082b71c228c7e5a8

**Comment by hnq90** [comment]
@spruce-bruce I used this snippet in my previous project: https://gist.github.com/hnq90/08237fa8d60c7f77690a7a3d1191a5d0
