### ISSUE TITLE
Inserting Null into a Table on Android using Bound Parameters inserts the String "NULL" instead.

### ISSUE THREAD

**Issue by Ayiga** [craftzdog/react-native-sqlite-2#26]
Greetings,

Whenever you attempt to insert a `NULL` value as a `column` on a `table` on an `Android` device, a `String` of `"NULL"` gets inserted instead.

For example, consider the behavior of the following test case.
```javascript
db.transaction((tx) => {
  tx.executeSql('CREATE TABLE IF NOT EXISTS null_test (id INTEGER PRIMARY KEY, value STRING)', []);
  tx.executeSql('INSERT INTO null_test (value) VALUES (?)', [null]);
  tx.executeSql('SELECT value FROM null_test', [],
    (_, result) => {
      const { rows } = result;
      for (let i = 0; i < rows.length; i += 1) {
        const item = rows.item(i);
        console.log(i, item); // 0 {value: "NULL"}
      }
    });
  tx.executeSql('SELECT COUNT(*) as count FROM null_test WHERE value IS NULL', [],
    (_, result) => {
      const { rows } = result;
      for (let i = 0; i < rows.length; i += 1) {
        const item = rows.item(i);
        console.log(i, item); // 0 {count: 0}
      }
  });
  tx.executeSql('DROP TABLE IF EXISTS null_test', []);
});

```

One would expect the answers to be ```{value: null}``` and ```{count: 1}``` instead.  This issue, ultimately, stems from the [`convertParamsToStringArray`](https://github.com/craftzdog/react-native-sqlite-2/blob/c41c97b6ab4386e5261d736a8d78a531fa086421/android/src/main/java/dog/craftz/sqlite_2/RNSqlite2Module.java#L316-L333) function, and more specifically it's use in the [`doUpdateInBackgroundAndPossiblyThrow`](https://github.com/craftzdog/react-native-sqlite-2/blob/c41c97b6ab4386e5261d736a8d78a531fa086421/android/src/main/java/dog/craftz/sqlite_2/RNSqlite2Module.java#L124) method.

[This **is** also an issue in the original cordova plugin](https://github.com/nolanlawson/cordova-plugin-sqlite-2/issues/43).  Ultimately the cause of the issue is the `API` provided by `Android`'s `SQLite` library.  The [`compileStatement`](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#compileStatement(java.lang.String)) method allows for the binding of individual parameters, but it doesn't allow for a variable length `SELECT` statement.  Instead, in order to evaluate arbitrary `SQL` statements for `SELECT` statements [`rawQuery`](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#rawQuery%28java.lang.String%2C%20java.lang.String[]%29) must be used. [`rawQuery`](https://developer.android.com/reference/android/database/sqlite/SQLiteDatabase.html#rawQuery%28java.lang.String%2C%20java.lang.String[]%29) only allows for a `String[]` as bound arguments.  As such, it's certainly influenced the decision to use [`convertParamsToStringArray`](https://github.com/craftzdog/react-native-sqlite-2/blob/c41c97b6ab4386e5261d736a8d78a531fa086421/android/src/main/java/dog/craftz/sqlite_2/RNSqlite2Module.java#L316-L333) in both places.

The fix is relatively straight forward, since the plugin is using [`compileStatement `](https://github.com/craftzdog/react-native-sqlite-2/blob/c41c97b6ab4386e5261d736a8d78a531fa086421/android/src/main/java/dog/craftz/sqlite_2/RNSqlite2Module.java#L121) and that allows for individual parameters to be bound, we can just do that, and resolve the issue automatically.

It would likely still be an issue for binding `NULL` in a `SELECT` statement, but it's not as a likely for that to occur, and I'm not certain how one gets around that while using any `query` method.

Thanks for your time, and the plugin,

Expect a `Pull Request` Shortly,

Thanks,

~ Ayiga

**Comment by craftzdog** [comment]
Hi,

Thanks for the bug report.
I tried to reproduce this problem but couldn't with following steps:

```
react-native init Sqlite2App
cd Sqlite2App
npm install react-native-sqlite-2
react-native link
```

Then edit `App.js` like so:

```js
import React, { Component } from 'react'
import {
  StyleSheet,
  Text,
  View,
  ListView
} from 'react-native'

import SQLite from 'react-native-sqlite-2'

const database_name = 'test.db'
const database_version = '1.0'
const database_displayname = 'SQLite Test Database'
const database_size = 200000
let db

export default class ReactNativeSQLite2Test extends Component {
  componentDidMount () {
    this.test()
  }

  test () {
    db = SQLite.openDatabase(database_name, database_version, database_displayname, database_size, this.openCB, this.errorCB)
    db.transaction((tx) => {
      tx.executeSql('CREATE TABLE IF NOT EXISTS null_test (id INTEGER PRIMARY KEY, value STRING)', []);
      tx.executeSql('INSERT INTO null_test (value) VALUES (?)');
      tx.executeSql('SELECT value FROM null_test', [],
        (_, result) => {
          const { rows } = result;
          for (let i = 0; i < rows.length; i += 1) {
            const item = rows.item(i);
            console.log(i, item); // 0 {value: "NULL"}
          }
        });
      tx.executeSql('SELECT COUNT(*) as count FROM null_test WHERE value IS NULL', [],
        (_, result) => {
          const { rows } = result;
          for (let i = 0; i < rows.length; i += 1) {
            const item = rows.item(i);
            console.log(i, item); // 0 {count: 0}
          }
        });
      tx.executeSql('DROP TABLE IF EXISTS null_test', []);
    });
  }

  render () {
    return (
      <View style={styles.container}>
        <Text>
          Test
        </Text>
      </View>
    )
  }
};

var styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF'
  }
})
```

Then run the app:

```
react-native run-android
```

The result was as expected:

<img width="203" alt="screen shot 2018-03-17 at 15 38 02" src="https://user-images.githubusercontent.com/1332805/37552488-e2375f9c-29f9-11e8-9f12-baa3834bee78.png">

I checked it on Android 5.1 and 8.0.

**Comment by Ayiga** [comment]
Sorry about that @craftzdog it looks like the `INSERT` query isn't passing `NULL` as a bound argument, which it needs to be.

```javascript
db.transaction((tx) => {
  tx.executeSql('CREATE TABLE IF NOT EXISTS null_test (id INTEGER PRIMARY KEY, value STRING)', []);
  tx.executeSql('INSERT INTO null_test (value) VALUES (?)', [null]);
  tx.executeSql('SELECT value FROM null_test', [],
    (_, result) => {
      const { rows } = result;
      for (let i = 0; i < rows.length; i += 1) {
        const item = rows.item(i);
        console.log(i, item); // 0 {value: "NULL"}
      }
    });
  tx.executeSql('SELECT COUNT(*) as count FROM null_test WHERE value IS NULL', [],
    (_, result) => {
      const { rows } = result;
      for (let i = 0; i < rows.length; i += 1) {
        const item = rows.item(i);
        console.log(i, item); // 0 {count: 0}
      }
  });
  tx.executeSql('DROP TABLE IF EXISTS null_test', []);
});
```

**Comment by craftzdog** [comment]
Okay, I confirmed the problem.

**Comment by craftzdog** [comment]
Merged #27

**Comment by seftrick** [comment]
We still have this issue.

**Comment by Ash-faq** [comment]
How can i use Pre-populated SQLite database from my app
