### ISSUE TITLE
A problem occurred configuring project ':app'.

### ISSUE THREAD

**Issue by RasoolF** [craftzdog/react-native-sqlite-2#29]
I install and use react-native-sql-2 step by step from site . but i got this error
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':react-native-sqlite-2'.
      > Could not resolve all dependencies for configuration ':react-native-sqlite-2:classpath'.
         > Could not resolve com.android.tools.build:gradle:1.3.1.
           Required by:
               KhabarApp:react-native-sqlite-2:unspecified
            > Could not resolve com.android.tools.build:gradle:1.3.1.
               > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/1.3.1/gradle-1.3.1.pom'.
                  > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/1.3.1/gradle-1.3.1.pom'.
                     > Connect to jcenter.bintray.com:443 [jcenter.bintray.com/75.126.118.188] failed: Connection timed out: connect
Please Help me Solve this problem . Thanks in advanced.

**Comment by craftzdog** [comment]
Google it with `gradle jcenter.bintray.com failed: Connection timed out`

**Comment by craftzdog** [comment]
Sorry, the installation instruction was incorrect.
I just fixed that so please check your configuration again along this change: https://github.com/craftzdog/react-native-sqlite-2/commit/8216cb6262ccd37c0ab302196be87c2d28343319
