### ISSUE TITLE
SQLCipher support?

### ISSUE THREAD

**Issue by vladikoff** [craftzdog/react-native-sqlite-2#32]
Hey, is there a way to add SQLCipher to this project? 

In the original project there is a fork with this: https://github.com/axsy-dev/react-native-sqlcipher-storage

Ref: https://github.com/andpor/react-native-sqlite-storage/issues/208

**Comment by craftzdog** [comment]
I'm not sure.
Feel free to fork this repo.

**Comment by scottwio** [comment]
Would be good to get SQLCipher support

**Comment by sreejithkrishnanr** [comment]
For SQLCipher support (Android/iOS) you can use this fork https://github.com/sreejithkrishnanr/react-native-sqlite-2
