### ISSUE TITLE
Getting UWP version compatibility issues while configuring with react-native-windows (UWP)

### ISSUE THREAD

**Issue by Sunny-Nishan** [craftzdog/react-native-sqlite-2#35]
![buildissue](https://user-images.githubusercontent.com/23293248/42461621-938fc158-83be-11e8-9f66-edf2629e4dc7.png)
I am getting this error while running react-native run-windows.
I just followed the steps to configure for UWP. Do I need to change SDK version to make it work? 

Thanks in advance!

**Comment by Sunny-Nishan** [comment]
I managed to solve this by changing version numbers in package.json of RNSqlite2 solution project.

![solution](https://user-images.githubusercontent.com/23293248/42463796-d45f1f48-83c4-11e8-8ee7-014aaaf7eaf2.png)

**Comment by ethanx94** [comment]
See https://github.com/craftzdog/react-native-sqlite-2/pull/24
