### ISSUE TITLE
How to pre-populate db in ios ? 

### ISSUE THREAD

**Issue by kaiyes** [craftzdog/react-native-sqlite-2#36]
Hi, 
How to pre-populate db in ios ?  I added a www folder and added a pre-populated db there. But Ain't showing up. The test case works just fine. Am I making any mistake locating the db file ?  Tried both `~sideline-app.db` and `~/www/sideline-app/db`
![screen shot 2018-07-15 at 6 49 02 pm](https://user-images.githubusercontent.com/5293742/42734093-cf7bf204-885f-11e8-9a37-e8d9073274ec.png)

![screen shot 2018-07-15 at 7 07 10 pm](https://user-images.githubusercontent.com/5293742/42734234-54b3f2a8-8862-11e8-96f4-074af8ee7de5.png)

**Comment by craftzdog** [comment]
Currently `createFromLocation` is not supported. PR would be welcomed.

**Comment by kaiyes** [comment]
@craftzdog  thanks a lot for answering. So where do I put a pre-populated db in ios if I intend to use one ?  I saw it is possible in windows https://github.com/craftzdog/react-native-sqlite-2/issues/4

**Comment by craftzdog** [comment]
A path for db is manipulated here:

https://github.com/craftzdog/react-native-sqlite-2/blob/master/ios/RNSqlite2.m#L56

So you have to copy your pre-populated db to the equivalent path.
Here is a code to get a destination path:

```objective-c
NSString* dbName = @"YOUR_DB";
NSString *libDir = [NSSearchPathForDirectoriesInDomains(NSLibraryDirectory, NSUserDomainMask, YES) objectAtIndex: 0];
NSString* dbPath = [[libDir stringByAppendingPathComponent:@"NoCloud"] stringByAppendingPathComponent: dbName];
```
