### ISSUE TITLE
Where I can see API docs for using this lib?

### ISSUE THREAD

**Issue by NelGarbuzova** [craftzdog/react-native-sqlite-2#39]
I can't find any documentation about API. How can I use this plugin, which methods I should use? If there is any docs about plugin's API, can you please share link with me?

**Comment by craftzdog** [comment]
Read the usage section: https://github.com/craftzdog/react-native-sqlite-2#usage

**Comment by NelGarbuzova** [comment]
@craftzdog is this lib supports 'UPDATE' query?

**Comment by craftzdog** [comment]
This is a bridge for SQLite3. Basically everything it provides is supported. So you have to read the SQLite3 documentations.

**Comment by NelGarbuzova** [comment]
I create table.
```
DatabaseService.openDatabase();
DatabaseService.createTable('Extent', 'id INTEGER PRIMARY KEY NOT NULL, min_x FLOAT, min_y FLOAT, max_x FLOAT, max_y FLOAT, srid TEXT');
```
Then I insert values into the row with id = 0;
`txn.executeSql('INSERT INTO Extent (id, min_x, min_y, max_x, max_y, srid) VALUES (1.22, 1.24, 0.56, -1.12, "3401");', []);`
I use sql query to update row
`txn.executeSql('UPDATE Extent SET min_x=1.23 WHERE id=0;', []);`
but row values doesn't update.

**Comment by jabzum** [comment]
@NeliHarbuzava  Hi, could you somehow update a row?
