### ISSUE TITLE
How to use with existing database on Windows?

### ISSUE THREAD

**Issue by metalmalte** [craftzdog/react-native-sqlite-2#4]
Hi,

thanks so much for your work! Is it possible to use an existing database for windows and how would you do that?

Cheers

**Comment by craftzdog** [comment]
It depends on what kind of database you're using.
Cc: @hnq90

**Comment by hnq90** [comment]
@metalmalte Which database are you using?

**Comment by hnq90** [comment]
@metalmalte Sorry, it's not supported yet. We will implement it soon.

**Comment by hnq90** [comment]
@metalmalte Did you try this?
```
import SQLite from 'react-native-sqlite-2';

const db = SQLite.openDatabase('test.db', '1.0', '', 1);
db.transaction(function (txn) {
  txn.executeSql('DROP TABLE IF EXISTS Users', []);
  txn.executeSql('CREATE TABLE IF NOT EXISTS Users(user_id INTEGER PRIMARY KEY NOT NULL, name VARCHAR(30))', []);
  txn.executeSql('INSERT INTO Users (name) VALUES (:name)', ['nora']);
  txn.executeSql('INSERT INTO Users (name) VALUES (:name)', ['takuya']);
  txn.executeSql('SELECT * FROM `users`', [], function (tx, res) {
    for (let i = 0; i < res.rows.length; ++i) {
      console.log('item:', res.rows.item(i));
    }
  });
});
```

**Comment by zerglingno1** [comment]
just using 
`const db = SQLite.openDatabase('test.db', '1.0', '', 1);
`
if 'test.db' is exist on app localstorage it will open that database , if not it will create new database

**Comment by metalmalte** [comment]
Thanks for all your help! The problem is, that the database itself seems to be never found at all. No matter where I store it. I tried to store it in the JS bundle, in the UWP assets folder and saving it in the root UWP directory. In all of these three cases, the framework will create a new database.

**Comment by zerglingno1** [comment]
Hi @metalmalte have you try ? 
C:\Users\Your-user-name\AppData\Local\Packages\your-app-package\LocalState
All database file will be store here .
If you store database in  JS bundle, UWP assets folder, root UWP directory you must write copy it to localstorage : 
`
StorageFile file = await StorageFile.GetFileFromApplicationUriAsync(
    new Uri("ms-appx:///Assets/database-name.db"));

await file.CopyAsync(ApplicationData.Current.LocalFolder, "database-name.db");
`

**Comment by metalmalte** [comment]
Thanks @zerglingno1 ! Thanks to you, I got it running now 👍
