### ISSUE TITLE
Could not find com.android.tools.build:gradle:2.3.3

### ISSUE THREAD

**Issue by AnneJackal** [craftzdog/react-native-sqlite-2#46]
Hello

what should I do?
Today i update gradle 4.6 version, then install and link react-native-sqlite-2 package.  

Sync Failed: 
Could not find com.android.tools.build:gradle:2.3.3.
Searched in the following locations:
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
    file:/C:/Program Files/Android/Android Studio/gradle/m2repository/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
    https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.pom
    https://jcenter.bintray.com/com/android/tools/build/gradle/2.3.3/gradle-2.3.3.jar
Required by:
    project :react-native-sqlite-2

https://jcenter.bintray.com/com/android/tools/build/gradle/  --- The requested path was not found.

**Comment by anderssv** [comment]
I get a similar error:

`A problem occurred configuring project ':react-native-sqlite-2'.
> Could not resolve all artifacts for configuration ':react-native-sqlite-2:classpath'.
   > Could not find any matches for com.android.tools.build:gradle:2.3.+ as no versions of com.android.tools.build:gradle are available.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/tools/build/gradle/maven-metadata.xml
         https://jcenter.bintray.com/com/android/tools/build/gradle/
     Required by:
         project :react-native-sqlite-2
`

Any clues as to what might cause this?

**Comment by joe-pritchard** [comment]
Having the same issue. Manually updating the packages build.gradle (bad I know, but I was in a hurry) to match my project's fixed the issue for now. This is what I'm using:

```
repositories {
        jcenter()
        mavenCentral()
        mavenLocal()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
    }
```

**Comment by sheva007** [comment]
@anderssv it happened to me when upgrading RN to 57. I see several commits to the repo that will fix this issue when they are released
@joe-pritchard I had to do the same thing to work on the project, waiting for the newer release of the repo

**Comment by craftzdog** [comment]
Hi there,

After having some googling I found some information about this issue.

https://github.com/oblador/react-native-vector-icons/issues/910#issuecomment-446302095

> Some packages were mistakenly removed by Google., and they are currently working on putting them back: https://issuetracker.google.com/issues/120759347.

The 2.3.3 version is looking for a file that has dissappeared from jcenter and that causes the error.

According to [this thread](https://github.com/DylanVann/react-native-fast-image/issues/366), you can avoid this error by adding it to your `android/build.gradle` like so:

```gradle
subprojects {project ->
    if (project.name.contains('react-native-sqlite-2')) {
        buildscript {
            repositories {
                maven { url "https://dl.bintray.com/android/android-tools/"  }
            }
            dependencies {
                classpath "com.android.tools.build:gradle:2.3.0"
            }
        }
    }
}
```

At the moment I don't have time to check if it works, but I believe it should work.

**Comment by AnneJackal** [comment]
That configuration is worked well. Thank you all :) 

> Hi there,
> 
> After having some googling I found some information about this issue.
> 
> [oblador/react-native-vector-icons#910 (comment)](https://github.com/oblador/react-native-vector-icons/issues/910#issuecomment-446302095)
> 
> > Some packages were mistakenly removed by Google., and they are currently working on putting them back: https://issuetracker.google.com/issues/120759347.
> 
> The 2.3.3 version is looking for a file that has dissappeared from jcenter and that causes the error.
> 
> According to [this thread](https://github.com/DylanVann/react-native-fast-image/issues/366), you can avoid this error by adding it to your `android/build.gradle` like so:
> 
> ```groovy-gradle
> subprojects {project ->
>     if (project.name.contains('react-native-sqlite-2')) {
>         buildscript {
>             repositories {
>                 maven { url "https://dl.bintray.com/android/android-tools/"  }
>             }
>             dependencies {
>                 classpath "com.android.tools.build:gradle:2.3.0"
>             }
>         }
>     }
> }
> ```
> 
> At the moment I don't have time to check if it works, but I believe it should work.
