### ISSUE TITLE
Row is too big to fit in the cursor window required pos 2 in Android 

### ISSUE THREAD

**Issue by qdevelopergithub** [craftzdog/react-native-sqlite-2#50]
Hi , i am storing a JSON file as a text field of sqlite. 
In Android, i am getting the error "row is too big to fit in the cursor window required pos 2" while getting it from the sqlite.but in ios same thing is working fine.

**Comment by craftzdog** [comment]
This is an Android SQLite3 problem and nothing to do with this plugin.

**Comment by craftzdog** [comment]
See https://github.com/craftzdog/react-native-sqlite-2/issues/57#issuecomment-491156124
