### ISSUE TITLE
Production

### ISSUE THREAD

**Issue by sm2017** [craftzdog/react-native-sqlite-2#6]
I want to know , is `craftzdog/react-native-sqlite-2` stable and production-ready?
Can I use this in my next big project?

**Comment by hnq90** [comment]
@sm2017 We haven't used it on any production app. So please use it at your own risk.
Thanks.

**Comment by craftzdog** [comment]
Hi.
This library is made for my own project called [Inkdrop](https://www.inkdrop.info/) which is already available on production (iOS/Android).
The codebase for iOS and Android was ported from [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2) which is ensured stable.
For windows, as @hnq90 said it's not used on production yet.
