### ISSUE TITLE
[Error: No useable methode found:["native","idb","localstorage"]

### ISSUE THREAD

**Issue by zhyafe** [craftzdog/react-native-sqlite-2#67]
## problem：
react-native use RxDB,  I chose react-native-sqlite as an adapter ，When debugging mode is turned off，I got this error '[Error: No useable methode found:["native","idb","localstorage"]',
but Turning on debuge is normal.

## code:
```js
import * as RxDB from 'rxdb'
import SQLite from 'react-native-sqlite-2'
import SQLiteAdapterFactory from 'pouchdb-adapter-react-native-sqlite'
const SQLiteAdapter = SQLiteAdapterFactory(SQLite)
RxDB.plugin(SQLiteAdapter)

let db = await RxDB.create({
        name: "userId",
        adapter: 'react-native-sqlite',
      })
```
## console：

![image](https://user-images.githubusercontent.com/24636373/66891936-e39d5400-f01c-11e9-9754-c5e584b5ffae.png)

**Comment by nerfpops** [comment]
You need to set multiInstance to false.

```javascript
let db = await RxDB.create({
  name: "userId",
  adapter: 'react-native-sqlite',
  multiInstance: false // <-- Here
})
```

**Comment by zhyafe** [comment]
@nerfpops  thank you
