### ISSUE TITLE
Android issue with syncing large attachments

### ISSUE THREAD

**Issue by swhamilton** [craftzdog/react-native-sqlite-2#71]
I'm experiencing an Android issue in RN 60.5 that's not present in the demo RN 59.1.
https://github.com/craftzdog/pouchdb-react-native-demo

iOS does not have this issue.

When syncing an attachment (image) of size from 1mb to 10mb it works fine in the demo and successfully syncs. However, when running the identical code using RN 60.5 and any file over 1.6mb, I get an error:

```
Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'length' of null
TypeError: Cannot read property 'length' of null
    at parseHexString
    at SQLTask.sqlCallback
    at blob
    at onSuccess
    at tryCallOne
    at blob
    at blob
    at _callTimer
    at _callImmediatesPass
    at Object.callImmediates
```

I'm pretty sure this issue comes from something failing within the WebSQL transaction process:
https://github.com/nolanlawson/node-websql/blob/ab6d7e06e00909046b98250da71248802935a284/lib/websql/WebSQLTransaction.js#L54

I have the same setup in the demo app and the RN 60.5 test app with the same code MainApplication.java change:

```
try {
  Field field = CursorWindow.class.getDeclaredField("sCursorWindowSize");
  field.setAccessible(true);
  field.set(null, 100 * 1024 * 1024); //the 100MB is the new size
} catch (Exception e) {
  if (e != null) {
    e.printStackTrace();
  }
}
```
There also seems to be an identical issue listed here, but this from 2016:
https://github.com/pouchdb/pouchdb/issues/5500#issue-167407541

I have searched for differences between RN 59.1 and 60.5, but can't find any reason why there would be a difference.

**Comment by craftzdog** [comment]
Does it also happen with react-native-sqlite-2@3.0.1?

**Comment by swhamilton** [comment]
@craftzdog I also tested with the latest react-native-sqlite-2@3.0.1 but still experienced the issue. I also noticed that the Android studio logs indicated it was CursorWindow issue...even with the MainApplication.java fix.

Would a demo RN app be enough to inspect? I can get that updated tomorrow if it would be helpful.

**Comment by Dhurzo** [comment]
Hello,

I was experiencing this issue with RN 61.5 & react-native-sqlite-2: 3.0.1. I solved the problem downgrading react-native-sqlite-2 to 2.0.4 and increasing the cursor as is described in the README:

`
try {
  Field field = CursorWindow.class.getDeclaredField("sCursorWindowSize");
  field.setAccessible(true);
  field.set(null, 100 * 1024 * 1024); //the 100MB is the new size
} catch (Exception e) {
  if (DEBUG_MODE) {
    e.printStackTrace();
  }
}
`

Hope this helps.

**Comment by craftzdog** [comment]
Since `react-native-sqlite-2 >= 3.0.0` uses [sqlite-android](https://github.com/requery/sqlite-android) for its SQLite engine, the package of `CursorWindow` class should be `io.requery.android.database` instead of `android.database.CursorWindow`.

**Comment by Dhurzo** [comment]
I am facing the same issue even changing the libary to io.requery.android.database

**Comment by craftzdog** [comment]
@swhamilton Yes, please.

**Comment by sanders-vag** [comment]
@Dhurzo thanks for sharing, you saved my day! I had the same issue and I was able to make it work downgrading to 2.0.4 and following the instructions in README to increase file size.

**Comment by sanders-vag** [comment]
> Hello,
> 
> I was experiencing this issue with RN 61.5 & react-native-sqlite-2: 3.0.1. I solved the problem downgrading react-native-sqlite-2 to 2.0.4 and increasing the cursor as is described in the README:
> 
> `try { Field field = CursorWindow.class.getDeclaredField("sCursorWindowSize"); field.setAccessible(true); field.set(null, 100 * 1024 * 1024); //the 100MB is the new size } catch (Exception e) { if (DEBUG_MODE) { e.printStackTrace(); } }`
> 
> Hope this helps.

@Dhurzo thanks for sharing, you saved my day! I had the same issue and I was able to make it work downgrading to 2.0.4 and following the instructions in README to increase file size.

**Comment by craftzdog** [comment]
Unfortunately, it turns out that [sqlite-android](https://github.com/requery/sqlite-android) does not support changing the default cursor window size.
Use v2 instead to solve this issue.
I'm not planning to revert this change because I'd rather want the performance.

**Comment by zefranlopes** [comment]
Close the cursors opened previously, the code above seems valid, but investigating further I noticed that some cursors still needed to close.
