### ISSUE TITLE
TypeORM support

### ISSUE THREAD

**Issue by likern** [craftzdog/react-native-sqlite-2#73]
Does this library is compatible with https://github.com/andpor/react-native-sqlite-storage? It is said it's a drop-replacement of react-native-sqlite-storage, but at the same time saying it has WebSQL-compatible API.

It's not clear can I use it with TypeORM, which support react-native-sqlite-storage.

**Comment by craftzdog** [comment]
This module is nothing to do with ORMs. You should try yourself to check if it works.
If TypeORM is compatible with WebSQL, go ahead.
