### ISSUE TITLE
Android boolean query arg are inversed

### ISSUE THREAD

**Issue by jdextraze** [craftzdog/react-native-sqlite-2#74]
The Android code convert a `true` boolean to `0` and a `false` one to `1`.

See this line: https://github.com/craftzdog/react-native-sqlite-2/blob/master/android/src/main/java/dog/craftz/sqlite_2/RNSqlite2Module.java#L344

Also since your are using SQLite 3.23+ now, you should be able to use `true` and `false` statement instead like the iOS code do.

**Comment by craftzdog** [comment]
Thanks for the report!

**Comment by craftzdog** [comment]
Landed in v3.1.0 🎉
