### ISSUE TITLE
Add Typescript support

### ISSUE THREAD

**Issue by likern** [craftzdog/react-native-sqlite-2#76]
It would be nice to have Typescript support through providing *.d.ts files.
Now I see this error.

![Снимок экрана от 2020-02-26 14-00-28](https://user-images.githubusercontent.com/842306/75338821-6c1be300-58a0-11ea-906f-9aa95bbf5915.png)

**Comment by craftzdog** [comment]
I'm not using TypeScript.
PR would be welcomed

**Comment by lindboe** [comment]
I've just been checking out this library today, so I'm not quite ready to help yet, but wanted to note if this is a drop-in replacement for react-native-sqlite-storage, then the types for that library should be a good place to start: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-sqlite-storage

**Comment by likern** [comment]
> I've just been checking out this library today, so I'm not quite ready to help yet, but wanted to note if this is a drop-in replacement for react-native-sqlite-storage, then the types for that library should be a good place to start: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-native-sqlite-storage

Yes. But, unfortunately, it's not a drop-in replacement. API is different and lacks almost all API for working with database.
For example, it's even not possible to close connection to database.

I've created my own fork of react-native-sqlite-storage https://github.com/breeffy/mobbly to be as drop-in replacement.
