### ISSUE TITLE
Where is the .db file ? On which path, the database file is stored ? 

### ISSUE THREAD

**Issue by TheRakeshPurohit** [craftzdog/react-native-sqlite-2#78]

**Comment by craftzdog** [comment]
https://github.com/craftzdog/react-native-sqlite-2/blob/master/ios/RNSqlite2.m#L55
https://github.com/craftzdog/react-native-sqlite-2/blob/master/android/src/main/java/dog/craftz/sqlite_2/RNSqlite2Module.java#L221

**Comment by TheRakeshPurohit** [comment]
Thank you for your reply !

**Comment by TheRakeshPurohit** [comment]
Would you mind helping me to prepopulate a db file ?

**Comment by craftzdog** [comment]
That's duplicated of https://github.com/craftzdog/react-native-sqlite-2/issues/54.
I made this library because it was necessary for my project.
But I don't need pre-populated database, so it is not planned to be supported.
I'd appreciate PRs for that.

**Comment by TheRakeshPurohit** [comment]
The .db file is not accessible with file manager on my physical android device. It needs root user(jailbreak or rooted device).

Any link or solution for `this.context.getFilesDir()` ??

**Comment by kalpeshm07** [comment]
where this .db file location in windows
