### ISSUE TITLE
Support for react-native-macos

### ISSUE THREAD

**Issue by ospfranco** [craftzdog/react-native-sqlite-2#81]
Hi! I'm doing a react-native-macos project and it would be great if I could use this adapter (in conjunction with rxdb), would it be possible to add support for macos?

**Comment by craftzdog** [comment]
Thanks for the PR.
Has it been solved with https://github.com/craftzdog/react-native-sqlite-2/pull/82 ?

**Comment by ospfranco** [comment]
yeah, I will close #82, sorry about formatting

**Comment by ospfranco** [comment]
@craftzdog is there any timeline for this change to be published?

**Comment by craftzdog** [comment]
okay, will release it next week

**Comment by craftzdog** [comment]
See https://github.com/craftzdog/react-native-sqlite-2/pull/82#discussion_r454760309

**Comment by elcssmouhsine** [comment]
hello any updates on this

**Comment by ospfranco** [comment]
support is already merged on master, not released yet but you can use it directly, there is a new PR #84 to take care of a small detail I oversaw but it is functional

**Comment by craftzdog** [comment]
Anything to document about macOS before publishing it?
I don't know but do you have to run commands something like `pod install`?
If so, it would be nice to update README.

**Comment by ospfranco** [comment]
Same steps as iOS, `pod install` is the only thing that is necessary

**Comment by craftzdog** [comment]
Okay

**Comment by craftzdog** [comment]
Landed in v3.1.0 🎉
