### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by craftzdog** [craftzdog/react-native-sqlite-2#9]
To ensure the stability of this module, we'd like to add tests because any changes may affect each platform implementations.
I believe it would be good to import tests from Nolan's [cordova-plugin-sqlite-2](https://github.com/nolanlawson/cordova-plugin-sqlite-2).
Since I have a lack of experience in tests for React Native modules, I would appreciate any contribution for it!

**Comment by craftzdog** [comment]
react-native-sqlite-storage's tests would be also helpful:
https://github.com/andpor/react-native-sqlite-storage/tree/master/test

**Comment by craftzdog** [comment]
We might need projects for testing for each platforms because [jest](http://facebook.github.io/jest/docs/tutorial-react-native.html) doesn't support testing components relying on native code.

**Comment by hnq90** [comment]
@craftzdog I think we should add unit tests for each platforms (XCTest for iOS, NUnit for Windows and JUnit for Android)

**Comment by craftzdog** [comment]
Using `react-native-sqlite-storage`'s test script for now.
