### ISSUE TITLE
bump websql version

### ISSUE THREAD

**Issue by technowizard** [craftzdog/react-native-sqlite-2#93]
Hello, I was using the `react-native-sqlite-2` and it has a dependency to [websql](https://github.com/nolanlawson/node-websql)

I recently asked the maintainer of websql to update one of its dependencies, now it has been updated to [2.0.0](https://github.com/nolanlawson/node-websql/blob/master/CHANGELOG.md#200). Here is the [issue](https://github.com/nolanlawson/node-websql/issues/32) and [PR](https://github.com/nolanlawson/node-websql/pull/33) regarding to this

Would you be able to update the websql version to match the current version? Thanks in advance

**Comment by craftzdog** [comment]
Great, will work on it
