### ISSUE TITLE
WebSQL threw an error [Error: database is locked (code 5): , while compiling: PRAGMA journal_mode]

### ISSUE THREAD

**Issue by timnodehk** [craftzdog/react-native-sqlite-2#95]
This is my first time to submit an issue.

After I update to version 3.2 or 3.3,

the below error will occur randomly after I close my react native app and re-open, then run db.put during development.

WebSQL threw an error [Error: database is locked (code 5): , while compiling: PRAGMA journal_mode]

Please let me know if I should provide more information detail.

**Comment by craftzdog** [comment]
Android or iOS? Please provide a reproduction code.

**Comment by timnodehk** [comment]
Android,

Sorry, I cannot reproduce every time, but I avoid the error by this way
`
// Original code
const db1 = new PouchDB('db1', adapter: 'react-native-slite');
const db2 = new PouchDB('db2', adapter: 'react-native-slite');

const something = await db1.get('something');
if(!something){
await db1.put({_id:'something'}); // sometimes throw the error after re-open app
}

// New code seem fix my problem
function createDb(dbName) {
  return new Promise(resolve=>{
      const db = new PouchDB(dbName, adapter: 'react-native-slite');
      PouchDB.on('created', function(newDbName){
        if(dbName === newDbName){
          resolve(db);
        }
      });
  });
}

const db1 = await createDb('db1');
const db2 = await createDb('db2');

const something = await db1.get('something');
if(!something){
 await db1.put({_id:'something'}); // the error seem go away
}
`
