### ISSUE TITLE
Is there any particular reason why NSURLIsExcludedFromBackupKey is needed?

### ISSUE THREAD

**Issue by gaodeng** [craftzdog/react-native-sqlite-2#97]
https://github.com/craftzdog/react-native-sqlite-2/blob/b4fc3ee4008cb1a2f41e39fb303e8fa87dc5d579/ios/RNSqlite2.m#L40

**Comment by craftzdog** [comment]
That's from this commit:

https://github.com/nolanlawson/cordova-plugin-sqlite-2/commit/bd8ec1c1e2315c4b2a657010f7573f886a4872ab

**Comment by gaodeng** [comment]
Thanks for the quick reply.

I don't see why NSURLIsExcludedFromBackupKey is needed from that commit, NSURLIsExcludedFromBackupKey would cause the user to be unable to back up the database.

**Comment by craftzdog** [comment]
I think not every app needs its database to be backed up by default, like static datasets. So, it'd be nice to be an option.
